CREATE ROLE Visitor WITH LOGIN
NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

GRANT CONNECT ON DATABASE postgres TO Visitor;
GRANT USAGE ON SCHEMA public TO Visitor;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO Visitor;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO Visitor;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO Visitor;

CREATE ROLE Administrator WITH LOGIN
SUPERUSER INHERIT NOREPLICATION;


--DROP OWNED BY
-- \conninfo

-- create table students (name varchar(30);
-- INSERT INTO students (name) VALUES ('petya');